mysql:
    host: 127.0.0.1
    port: 3306
    db: xie-blog
    config: charset=utf8mb4&parseTime=True&loc=Local
    username: root
    password: '@xjy158191'
    log-mode: error
logger:
    level: info
    prefix: '[GVB]'
    director: log
    show-line: true
    log-in-console: true
system:
    host: 0.0.0.0
    port: 8888
    env: production
redis:
    ip: 127.0.0.1
    port: 6379
    password: 158191xjy
    db-name: 0
    pool-size: 100
jwt:
    signing-key: ""
    expires-time: 7d
    buffer-time: 1d
    issuer: xiean
    signing-method: jwt.SigningMethodHS256
local:
    size: 10
    path: uploads/file
    store-path: uploads/file
qiniu:
    enable: true
    access_key: Wd11biHm1Z4Iqqqy_72fFXD8VAEEhtn1lZfiY_OH
    secret_key: xh-_XguHgJ8X441Gf411ed9Hq4C6wnJ1A0SfAe8K
    bucket: xiean173
    cdn: cdn.jaynxe.cn/
    zone: z2
    size: 5
    prefix: gvb
    use-https: false
    use-cdn-domains: false
email:
    host: smtp.qq.com
    port: 465
    senderEmail: 3187837714@qq.com
    password: eyswqhamukuideeg
    default-from-email: jaynex.cn
    use_ssl: false
    user_tls: false
qq:
    app_id: ""
    key: ""
    redirect: http://127.0.0.1:3000/login?flag=qq
site:
    name: xie-blog
    tagline: New Tagline for the Blog
    description: Updated description for the blog.
    url: http://newblogurl.com
    author_name: John Doe
    bio: Updated bio for the author.
    twitter: new_twitter_handle
    facebook: new_facebook_handle
    instagram: new_instagram_handle
    email: newemail@example.com
    phone: "+0987654321"
    address: |-
        123 Main Street
        Cityville, State 12345
        Country
