mysql:
  host: 127.0.0.1
  port: 3306
  db: xie-blog
  username: root
  password: "@xjy158191"
  config: charset=utf8mb4&parseTime=True&loc=Local
  # gorm的日志模式
  log-mode: error

system:
  host: "0.0.0.0"
  port: 8888
  env: info

logger:
  # 全局log的级别
  level: info
  prefix: "[GVB]"
  director: log
  show-line: true
  log-in-console: true