mysql:
  host: 127.0.0.1
  port: 3306
  db: xie-blog
  username: root
  password: "@xjy158191"
  log-level: error

system:
  host: "0.0.0.0"
  port: 8888
  env: local

logger:
  level: info
  prefix: "[GVB]"
  director: log
  show-line: true
  log-in-console: true