// Code generated by "stringer -type=ErrCode"; DO NOT EDIT.

package errhandle

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoError-0]
	_ = x[InnerError-1]
	_ = x[TokenError-2]
	_ = x[ParamsError-3]
	_ = x[UserExists-4]
	_ = x[UserNonExists-5]
	_ = x[PasswordInvalid-6]
	_ = x[PermissionDenied-7]
	_ = x[SexError-8]
	_ = x[NameExists-9]
	_ = x[EmailFormatError-10]
	_ = x[PasswordFormatError-11]
	_ = x[FileSizeTooLarge-12]
	_ = x[FileTypeNoMatch-13]
	_ = x[VerifyCodeError-14]
	_ = x[EmailIsDifferent-15]
	_ = x[MenuExists-16]
	_ = x[MenuNotExists-17]
	_ = x[TagExists-18]
	_ = x[TagNotExists-19]
	_ = x[ImageExists-20]
	_ = x[ImageNotExists-21]
	_ = x[OtherError-22]
}

const _ErrCode_name = "NoErrorInnerErrorTokenErrorParamsErrorUserExistsUserNonExistsPasswordInvalidPermissionDeniedSexErrorNameExistsEmailFormatErrorPasswordFormatErrorFileSizeTooLargeFileTypeNoMatchVerifyCodeErrorEmailIsDifferentMenuExistsMenuNotExistsTagExistsTagNotExistsImageExistsImageNotExistsOtherError"

var _ErrCode_index = [...]uint16{0, 7, 17, 27, 38, 48, 61, 76, 92, 100, 110, 126, 145, 161, 176, 191, 207, 217, 230, 239, 251, 262, 276, 286}

func (i ErrCode) String() string {
	if i < 0 || i >= ErrCode(len(_ErrCode_index)-1) {
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrCode_name[_ErrCode_index[i]:_ErrCode_index[i+1]]
}
